version: "3.5"

services:
  mymongo:
      image: mongo:latest
      volumes:
        - ./data/db:/data/db
      ports:
        - 27017:27017
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: express-graphql
    build: .
    volumes:
      - "./:/usr/src/app"
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 4000:4000